---
- name: Configure the NVIDIA Container Toolkit DNF repository
  ansible.builtin.get_url:
    url: "{{ container_toolkit_dnf_repository }}"
    # yamllint disable-line rule:quoted-strings
    dest: "/etc/yum.repos.d/{{ container_toolkit_repository_filename }}.repo"
    owner: root
    group: root
    mode: "0644"
